"""Add blog category model and enhance blog post with category is_featured read_time

Revision ID: 3c16ba1a75a1
Revises: cbbf32689581
Create Date: 2026-01-18 14:49:21.214072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c16ba1a75a1'
down_revision = 'cbbf32689581'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_categories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='hisi'
    )
    with op.batch_alter_table('blog_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hisi_blog_categories_slug'), ['slug'], unique=True)

    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('is_featured', sa.Boolean(), nullable=False, server_default='false'))
        batch_op.add_column(sa.Column('read_time', sa.String(length=50), nullable=True))
        batch_op.drop_constraint(batch_op.f('blog_posts_author_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['author_id'], ['id'], referent_schema='hisi')

    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('cart_items_product_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('cart_items_cart_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'products', ['product_id'], ['id'], referent_schema='hisi')
        batch_op.create_foreign_key(None, 'carts', ['cart_id'], ['id'], referent_schema='hisi')

    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('carts_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], referent_schema='hisi')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('categories_parent_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'categories', ['parent_id'], ['id'], referent_schema='hisi')

    with op.batch_alter_table('media_files', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('media_files_uploaded_by_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['uploaded_by'], ['id'], referent_schema='hisi')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('messages_recipient_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('messages_sender_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['recipient_id'], ['id'], referent_schema='hisi')
        batch_op.create_foreign_key(None, 'users', ['sender_id'], ['id'], referent_schema='hisi')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('notifications_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], referent_schema='hisi')

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('order_items_product_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('order_items_order_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'orders', ['order_id'], ['id'], referent_schema='hisi')
        batch_op.create_foreign_key(None, 'products', ['product_id'], ['id'], referent_schema='hisi')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('orders_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], referent_schema='hisi')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('payments_order_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'orders', ['order_id'], ['id'], referent_schema='hisi')

    with op.batch_alter_table('product_collections', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('product_collections_featured_image_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'media_files', ['featured_image_id'], ['id'], referent_schema='hisi')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('products_category_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['id'], referent_schema='hisi')

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('reviews_product_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('reviews_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], referent_schema='hisi')
        batch_op.create_foreign_key(None, 'products', ['product_id'], ['id'], referent_schema='hisi')

    with op.batch_alter_table('section_content', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('section_content_updated_by_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['updated_by'], ['id'], referent_schema='hisi')

    with op.batch_alter_table('user_addresses', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('user_addresses_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], referent_schema='hisi')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_addresses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('user_addresses_user_id_fkey'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('section_content', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('section_content_updated_by_fkey'), 'users', ['updated_by'], ['id'])

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('reviews_user_id_fkey'), 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('reviews_product_id_fkey'), 'products', ['product_id'], ['id'])

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('products_category_id_fkey'), 'categories', ['category_id'], ['id'])

    with op.batch_alter_table('product_collections', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('product_collections_featured_image_id_fkey'), 'media_files', ['featured_image_id'], ['id'])

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('payments_order_id_fkey'), 'orders', ['order_id'], ['id'])

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('orders_user_id_fkey'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('order_items_order_id_fkey'), 'orders', ['order_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('order_items_product_id_fkey'), 'products', ['product_id'], ['id'])

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('notifications_user_id_fkey'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('messages_sender_id_fkey'), 'users', ['sender_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('messages_recipient_id_fkey'), 'users', ['recipient_id'], ['id'])

    with op.batch_alter_table('media_files', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('media_files_uploaded_by_fkey'), 'users', ['uploaded_by'], ['id'])

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('categories_parent_id_fkey'), 'categories', ['parent_id'], ['id'])

    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('carts_user_id_fkey'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('cart_items_cart_id_fkey'), 'carts', ['cart_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('cart_items_product_id_fkey'), 'products', ['product_id'], ['id'])

    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('blog_posts_author_id_fkey'), 'users', ['author_id'], ['id'])
        batch_op.drop_column('read_time')
        batch_op.drop_column('is_featured')
        batch_op.drop_column('category')

    with op.batch_alter_table('blog_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hisi_blog_categories_slug'))

    op.drop_table('blog_categories', schema='hisi')
    # ### end Alembic commands ###
