"""aded phone column

Revision ID: 3edde1b7a39f
Revises: e7bc8aa9c39a
Create Date: 2025-11-27 17:31:27.294139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3edde1b7a39f'
down_revision = 'e7bc8aa9c39a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=13), nullable=True))
        batch_op.create_unique_constraint('uq_users_phone', ['phone'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_phone', type_='unique')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
