"""Add press page tables

Revision ID: cbbf32689581
Revises: b9bae5df90b7
Create Date: 2026-01-15 09:27:43.671574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbbf32689581'
down_revision = 'b9bae5df90b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collaborations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('partner', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image', sa.String(length=500), nullable=True),
    sa.Column('year', sa.String(length=4), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='hisi'
    )
    op.create_table('exhibitions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image', sa.String(length=500), nullable=True),
    sa.Column('gallery', sa.Text(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='hisi'
    )
    op.create_table('media_coverage',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('outlet', sa.String(length=200), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image', sa.String(length=500), nullable=True),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='hisi'
    )
    op.create_table('media_kit_config',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='hisi'
    )
    op.create_table('media_kit_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('file_size', sa.String(length=20), nullable=True),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='hisi'
    )
    op.create_table('press_contact',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='hisi'
    )
    op.create_table('press_hero',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('subtitle', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='hisi'
    )
    op.create_table('press_releases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='hisi'
    )
    op.create_table('speaking_engagements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('event', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('engagement_type', sa.String(length=50), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='hisi'
    )
    op.create_table('section_content',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('page_name', sa.String(length=50), nullable=False),
    sa.Column('section_name', sa.String(length=50), nullable=False),
    sa.Column('content_key', sa.String(length=100), nullable=False),
    sa.Column('content_value', sa.Text(), nullable=True),
    sa.Column('content_type', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['hisi.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('page_name', 'section_name', 'content_key', name='unique_section_content'),
    schema='hisi'
    )
    with op.batch_alter_table('section_content', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hisi_section_content_page_name'), ['page_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_hisi_section_content_section_name'), ['section_name'], unique=False)

    op.create_table('reviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['hisi.products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['hisi.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='hisi'
    )
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('blog_posts_author_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['author_id'], ['id'], referent_schema='hisi')

    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('cart_items_product_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('cart_items_cart_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'products', ['product_id'], ['id'], referent_schema='hisi')
        batch_op.create_foreign_key(None, 'carts', ['cart_id'], ['id'], referent_schema='hisi')

    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('carts_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], referent_schema='hisi')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('categories_parent_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'categories', ['parent_id'], ['id'], referent_schema='hisi')

    with op.batch_alter_table('media_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hisi_media_files_uploaded_by'))
        batch_op.drop_constraint(batch_op.f('media_files_uploaded_by_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['uploaded_by'], ['id'], referent_schema='hisi')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('messages_recipient_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('messages_sender_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['recipient_id'], ['id'], referent_schema='hisi')
        batch_op.create_foreign_key(None, 'users', ['sender_id'], ['id'], referent_schema='hisi')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hisi_notifications_user_id'))
        batch_op.drop_constraint(batch_op.f('notifications_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], referent_schema='hisi')

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('order_items_order_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('order_items_product_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'orders', ['order_id'], ['id'], referent_schema='hisi')
        batch_op.create_foreign_key(None, 'products', ['product_id'], ['id'], referent_schema='hisi')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('orders_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], referent_schema='hisi')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('payments_order_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'orders', ['order_id'], ['id'], referent_schema='hisi')

    with op.batch_alter_table('product_collections', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('product_collections_featured_image_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'media_files', ['featured_image_id'], ['id'], referent_schema='hisi')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('products_category_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['id'], referent_schema='hisi')

    with op.batch_alter_table('user_addresses', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('user_addresses_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], referent_schema='hisi')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_addresses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('user_addresses_user_id_fkey'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('products_category_id_fkey'), 'categories', ['category_id'], ['id'])

    with op.batch_alter_table('product_collections', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('product_collections_featured_image_id_fkey'), 'media_files', ['featured_image_id'], ['id'])

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('payments_order_id_fkey'), 'orders', ['order_id'], ['id'])

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('orders_user_id_fkey'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('order_items_product_id_fkey'), 'products', ['product_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('order_items_order_id_fkey'), 'orders', ['order_id'], ['id'])

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('notifications_user_id_fkey'), 'users', ['user_id'], ['id'])
        batch_op.create_index(batch_op.f('ix_hisi_notifications_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('messages_sender_id_fkey'), 'users', ['sender_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('messages_recipient_id_fkey'), 'users', ['recipient_id'], ['id'])

    with op.batch_alter_table('media_files', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('media_files_uploaded_by_fkey'), 'users', ['uploaded_by'], ['id'])
        batch_op.create_index(batch_op.f('ix_hisi_media_files_uploaded_by'), ['uploaded_by'], unique=False)

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('categories_parent_id_fkey'), 'categories', ['parent_id'], ['id'])

    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('carts_user_id_fkey'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('cart_items_cart_id_fkey'), 'carts', ['cart_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('cart_items_product_id_fkey'), 'products', ['product_id'], ['id'])

    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('blog_posts_author_id_fkey'), 'users', ['author_id'], ['id'])

    op.drop_table('reviews', schema='hisi')
    with op.batch_alter_table('section_content', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hisi_section_content_section_name'))
        batch_op.drop_index(batch_op.f('ix_hisi_section_content_page_name'))

    op.drop_table('section_content', schema='hisi')
    op.drop_table('speaking_engagements', schema='hisi')
    op.drop_table('press_releases', schema='hisi')
    op.drop_table('press_hero', schema='hisi')
    op.drop_table('press_contact', schema='hisi')
    op.drop_table('media_kit_items', schema='hisi')
    op.drop_table('media_kit_config', schema='hisi')
    op.drop_table('media_coverage', schema='hisi')
    op.drop_table('exhibitions', schema='hisi')
    op.drop_table('collaborations', schema='hisi')
    # ### end Alembic commands ###
